import pictureRoom from "../../assets/pictureRoom.jpg";

const dataRoom = [
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
    description:
      "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
  },
];
export default dataRoom;

// {
//   id: "1",
//   pictureLink: "",
//   building: 'H1'
//   floor: 'Tầng 1'
//   roomNumber: "100",
//   maxSeat: 8,
//   currentSeat: 1,
//   type: 0,
//   state: 1,
//   description:
//     "Phòng học hỗ trợ các thiết bị cơ bản như, đèn bàn, quạt, dây sạc, ổ điện ",
//   historyTime: "2025-04-04T16:04:43"
// },
