import pictureRoom from "../../assets/pictureRoom.jpg";

const dataRoom = [
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
];
export default dataRoom;
