import pictureRoom from "../../assets/pictureRoom.jpg";

const dataRoom = [
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 1,
    floor: 1,
    roomNumber: "100",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 2,
    floor: 1,
    roomNumber: "106",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "1",
    pictureLink: "",
    building: 3,
    floor: 3,
    roomNumber: "311",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
  {
    id: "0",
    pictureLink: "",
    building: 0,
    floor: 4,
    roomNumber: "411",
    maxSeat: 8,
    currentSeat: 1,
    type: 0,
    state: 1,
  },
];
export default dataRoom;
